### ISSUE TITLE
upgrade of large h2 db fails on 'Timeout trying to lock table "SYS"'

### ISSUE THREAD

**Issue by TobiasMarte** [gocd/gocd-database-migrator#10]
I have a 150gb h2db file.  I just upgraded from 18.9 to 20.0.4 with no issues, then ran the database migrator script.  It gets maybe aroud 10% into the record copy progress status, then fails with this 'Timeout trying to lock table "SYS"' exception and spits out some REALLY long SQL statement.  Googling this error I found that maybe the default LOCK_TIMEOUT is maybe to short, and I tried passing an increased one into the jdbc url but I still get the same issue.  I can't tell for certain if the increased LOCK_TIMEOUT is actually being set and used, as I don't know how to dump the current settings while it runs.  Any ideas on how to debug this further?

```
export JAVA_HOME=/opt/java/jdk1.8.0_201/; export PATH="$JAVA_HOME/bin:$PATH"
nohup ./gocd-database-migrator \
--insert \
--progress \
--source-db-url='jdbc:h2:/data/gocd-server-backup/gocdhost/data/gocd-db/db/h2db/cruise;LOCK_TIMEOUT=300000' \
--source-db-user='sa' \
--source-db-password='' \
--target-db-url='jdbc:h2:/data/gocd-server-backup/gocdhost/data/gocd-db/db/h2db/NEWLY_MIGRATED_cruise;LOCK_TIMEOUT=300000' \
--target-db-user='sa' \
--target-db-password='' \
> gocd-database-migrator-1.0.0/gocd_h2db_upgrade.log 2>&1 &
```

**Comment by TobiasMarte** [comment]
the SQL line associated with the exception is 12.5 million characters long.  

a few seconds later another exception is thrown and the upgrade job exits.


Caused by: liquibase.exception.DatabaseException: General error: "java.lang.IllegalStateException: Chunk 3747 not found [1.4.200/9]"; SQL statement:
CREATE INDEX PUBLIC.FK_MODIFIEDFILES_MODIFICATIONS ON PUBLIC.MODIFIEDFILES(MODIFICATIONID) [50000-200] [Failed SQL: (50000) CREATE INDEX PUBLIC.FK_MODIFIEDFILES_MODIFICATIONS ON PUBLIC.MODIFIEDFILES(MODIFICATIONID)]

**Comment by TobiasMarte** [comment]
If I re-run it I get basically the same errors at slightly different places, even if I drastically increase the LOCK_TIMEOUT.   Slightly different progress amount, error line, and chunk number.

**Comment by TobiasMarte** [comment]
I have given up and am starting from scratch with a new H2 db

**Comment by chadlwilson** [comment]
Since this is pretty old and stale, I'm going to close this now.

If anyone else is struggling with a really large DB, is getting a similar error, and wants to try and debug this further, we can re-open this.
