### ISSUE TITLE
Unset sequence values on converting H2 to Postgres 12

### ISSUE THREAD

**Issue by matwhite** [gocd/gocd-database-migrator#4]
After converting an H2 database to Postgres 12, we were unable to modify materials for pipelines in GoCD. The error message indicated a primary key overlap. An investigation revealed that a sequence ID was too low given the IDs present in the `materials` table. To fix it, we manually set the sequence ID forward to the maximum row ID on the `materials` table. Based on an unmodified/fresh database migration, the root cause appears to be that there are certain sequences with no value set during migration.

Evidence of Possible Root Cause:
```
gocd=> select sequencename from pg_sequences where last_value is null;
             sequencename
---------------------------------------
 accesstoken_id_seq
 agents_id_seq
 jobagentmetadata_id_seq
 materials_id_seq
 notificationfilters_id_seq
 pipelineselections_id_seq
 plugins_id_seq
 stageartifactcleanupprohibited_id_seq
 users_id_seq
```

Symptoms of Issue (when trying to update a material):
```
2020-08-18 16:55:12,206 WARN  [128@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:127 - [Material Update] Modification check failed for material: URL: git@gitXXXXXXX.git, Branch: updated_branch
org.springframework.dao.DataIntegrityViolationException: could not insert: [com.thoughtworks.go.domain.materials.git.GitMaterialInstance]; SQL [insert into materials (flyweightName, fingerprint, additionalData, url, username, branch, submoduleFolder, type) values (?, ?, ?, ?, ?, ?, ?, 'GitMaterial')]; constraint [materials_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [com.thoughtworks.go.domain.materials.git.GitMaterialInstance]
...
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "materials_pkey"

gocd=> select last_value from pg_sequences where sequencename = 'materials_id_seq';
 last_value
------------
        113

gocd=> select max(id) from materials;
 max
------
 1305
```

Fix (for symptom):
```
gocd=> select setval('materials_id_seq',1305);
 setval
--------
   1305

**Comment by maheshp** [comment]
@matwhite did you see any errors logged while running the migration?

On migration from H2 to PostgreSQL for the setting sequences the [query](https://github.com/gocd/gocd-database-migrator/blob/master/src/main/java/com/thoughtworks/go/dbsync/DbSync.java#L308) run is ` select setval('materials_id_seq', (select max(id) from MATERIALS));` which is similar what you have done.

**Comment by matwhite** [comment]
Unfortunately, I don't have access to any error information. We ran the migration across several GoCD servers and we had to set the sequence for the `materials`, `agents`, and `users` tables for all of them.

**Comment by maheshp** [comment]
I tried migrating a larger H2 db to PostgreSQL and I was not able to reproduce this issue. All the sequences were set as expected. 
If you can give more information or help us reproduce this issue, we can take a look at it.

**Comment by maheshp** [comment]
I tried migration on PostgreSQL 9.6.17, will give a shot on PostgreSQL 12 to see if this can be reproducible.
